version: "3.5"

services:
  api01: &api
    image: naelly/extratinhos:latest
    hostname: api01
    environment:
        ASPNETCORE_ENVIRONMENT: "Production"
        ConnectionStrings__DefaultConnection: "Server=db,1433;Database=extratinhos;User ID=sa;Password=Pa$$w0rd2024"
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
    networks:
        - api-network

  api02:
    <<: *api 
    hostname: api02
    ports:
      - "8082:8080"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"
    networks:
       - api-network

  db:
    container_name: mssql-db
    hostname: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa$$w0rd2024"
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: "Developer" 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    networks:
       - api-network

networks:
  api-network:
    driver: bridge
    name: extratinhos-network
